CREATE TABLE customers (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(255) NOT NULL,
                           email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        customer_id BIGINT NOT NULL,
                        status VARCHAR(50) NOT NULL,
                        CONSTRAINT fk_orders_customer
                            FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE order_item (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            product_id VARCHAR(255) NOT NULL,
                            price DECIMAL(19,2) NOT NULL,
                            quantity BIGINT NOT NULL,
                            order_id BIGINT,
                            CONSTRAINT fk_order_item_order
                                FOREIGN KEY (order_id) REFERENCES orders(id)
);